#
# clean - Clean up the directory.
#
clean : 
	rm -f *~ *.CKP *.ln *.BAK *.bak .*.bak \
		core errs \
		,* .emacs_* \
		tags TAGS \
		make.log MakeOut \
		*.old *.stdout *.out *.alquimia *.tec *.txt *.testlog

#
# clobber - Really clean up the directory.
#
clobber : clean $(SUBDIRS)

#
# FORCE - Null rule to force things to happen.
#
FORCE :

