#!/usr/bin/env python

def build(ctx):

    ctx.stlib(
        features = 'cxx cxxstlib',
        source = ['demo_utils.cc',
                  'demo_containers.cc',
                  'cfg_reader.cc',
                  'string_tokenizer.cc'],
        target = 'demoutils'
        )

    ctx.program(
        features = 'c cxx fc cxxprogram',
        source = ['batch_chem.cc'],
        includes = ['../alquimia/c', '../alquimia/c++'],
        use = ['alquimia_c',
               'alquimia_fortran',
               'alquimia_c++',
               'demoutils'],
        target = 'batch_chem'
        )

    ctx.install_files("${PREFIX}/bin", ['batch_chem'], chmod=0700)
